name = "yaibot"
main = "src/index.ts"
compatibility_date = "2025-06-14"
minify = true
upload_source_maps = true
preview_urls = false

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_id = "038cca91-b6d2-468c-91e0-a7e859cb30ee"
database_name = "inline"

# [vars.BOT_INFO]
# id = 7414779700
# is_bot = true
# first_name = "流典忆庭"
# username = "yet_another_inline_bot"
# can_join_groups = true
# can_read_all_group_messages = false
# supports_inline_queries = true
# can_connect_to_business = false
# has_main_web_app = false
